### ISSUE TITLE
Source code should look better on mobile

### ISSUE THREAD

**Issue by ry** [denoland/registry#103]
![IMG_4126](https://user-images.githubusercontent.com/80/59865709-c0f17c00-9357-11e9-8338-1aef4f016ac4.jpg)

The wrapping is annoying in this view. I think we should save space by removing line numbers.

Our code is 80 characters wide. Font size should be adjusted so that 80 columns can be displayed without scrolling horizontally.

**Comment by j-f1** [comment]
> The wrapping is annoying in this view. I think we should save space by removing line numbers.

That would disable the ability to select lines to permalink, although maybe that’s a good thing since it’s not possible to range select with a touchscreen
