### ISSUE TITLE
non-JS files look odd

### ISSUE THREAD

**Issue by ry** [denoland/registry#105]
https://deno.land/std/LICENSE

<img width="816" alt="Screen Shot 2019-06-20 at 2 14 58 PM" src="https://user-images.githubusercontent.com/80/59871540-d1105800-9365-11e9-8adb-bb2925145df4.png">

**Comment by j-f1** [comment]
Are you OK with switching to the expanded version of highlight.js with all 176 languages (18 kb → 185 kb) or should I stick with the current version which includes 24 languages?

**Comment by ry** [comment]
Probably 24 language version is fine?
