### ISSUE TITLE
auto-compile TS -> JS

### ISSUE THREAD

**Issue by ry** [denoland/registry#106]
Currently this works: https://deno.land/std/http/server.ts

It would also be nice if this worked too: https://deno.land/std/http/server.js

Where the server magically runs tsc on the file (without type checks) and produces the corresponding JS.

This would allow browsers to use deno modules.

**Comment by j-f1** [comment]
How about using the original URL so people can still host JS files? https://deno.land/std/http/server.ts?compile

**Comment by j-f1** [comment]
Also, duplicate of #39.

**Comment by ry** [comment]
oops - closing in favor of #39 .

> https://deno.land/std/http/server.ts?compile 

sure

**Comment by yordis** [comment]
@ry did you meant to close this one?

**Comment by ry** [comment]
thx
