### ISSUE TITLE
render markdown 

### ISSUE THREAD

**Issue by ry** [denoland/registry#108]
for https://deno.land/std/README.md

**Comment by j-f1** [comment]
Working on this.

**Comment by ry** [comment]
Please use the same libraries we use in deno/website https://github.com/denoland/deno/blob/77a00aef4cef31e1e76549b3fcef25f389c0ab84/website/manual.html#L29-L33

**Comment by j-f1** [comment]
![](https://user-images.githubusercontent.com/25517624/59882737-10986d80-9381-11e9-98c5-7c277593fd2a.png)

<img src="https://user-images.githubusercontent.com/25517624/59882789-2e65d280-9381-11e9-8fad-14bfb141b68e.png">

<img src="https://user-images.githubusercontent.com/25517624/59882767-21e17a00-9381-11e9-9c32-d7dc31224415.png">
