### ISSUE TITLE
Code should not wrap if there is enough screen real estate

### ISSUE THREAD

**Issue by ry** [denoland/registry#125]
<img width="1139" alt="Screen Shot 2019-07-09 at 2 53 52 PM" src="https://user-images.githubusercontent.com/80/60915307-8c3b5b00-a259-11e9-922e-061a399b9648.png">

https://deno.land/x/install@1a0c1e/install.ps1#L54

cc @j-f1

**Comment by j-f1** [comment]
[self-assign]

**Comment by j-f1** [comment]
oops, turns out deleting your only comment on an issue unassigns you. TIL.
