### ISSUE TITLE
Should we use username/library instead of just library to prevent conflicts? 

### ISSUE THREAD

**Issue by cardosomarcos** [denoland/registry#26]
I was looking for a library to deal with .env files and I didn't find any. So, I've made this library. I came here to publish it, but there was already a same propose library from pietvanzoen.

Would be nice to support, and also enforce, namespace or username before the library name.

Example: **cardosomarcos/dotenv**  instead of  **dotenv**.
```ts
import dotenv  from "https://deno.land/x/cardosomarcos/dotenv/index.ts";
// instead of
import dotenv  from "https://deno.land/x/dotenv/index.ts";
```

**Comment by j-f1** [comment]
IMO a registry should not have namespaced identifiers, especially since GitHub already provides this functionality, and [DenoPkg](https://github.com/denopkg/denopkg.com) makes it easier to import things from GitHub.

**Comment by tunnckoCore** [comment]
I'm wondering, why not just use the NPM infrastructure - e.g. unpkg? Of course, for things that are already published on npm. Or another alternative is just using the CDNs JSDelivr or another one. Their links might be a bit long, but we can stand as a "short url" for them.

@denopkg by @egoist is good one. Which currently uses Raw Github.
We can switch it to use some CDN and we will have access to both Github and NPM packages.

- https://denopkg.com/dotenv from npm/cdn (trying to resolve `/dotenv/index.ts`, `/dotenv/main.ts`, `dotenv/mod.ts`)
- https://denopkg.com/cardosomarcos/dotenv - from GitHub through CDN

**Comment by ExE-Boss** [comment]
**npm** uses the&nbsp;`@<username>/<package>` syntax for scoped packages.

**Comment by tomByrer** [comment]
I like enforcing username//lib.  Easy to anciently name packages the same, original repo is dead & maintainer is unresponsive so you have to fork to maintain, etc.

**Comment by zhaoyao91** [comment]
This issue may should be closed to prefer https://github.com/denoland/registry/issues/117
