### ISSUE TITLE
Styling deno.land/x/ and clickable links to repos

### ISSUE THREAD

**Issue by rista404** [denoland/registry#31]
Page https://deno.land/x/ is useful but lacks some minimal styling and clickable links to the github repositories. I would be happy to add that.

**Comment by ry** [comment]
Yes please! I've been meaning to do it, but haven't found time.

**Comment by rista404** [comment]
Happy to help! Should I parse the `https://raw.githubusercontent.com/.../...` links to get the repo url, or should I include the repo url as a separate field in `database.json`?

**Comment by ry** [comment]
@rista404 probably better to just add another field
