### ISSUE TITLE
Rather than redirect, fetch and serve.

### ISSUE THREAD

**Issue by ry** [denoland/registry#38]
When visiting a URL like this in a web browser: https://deno.land/x/std@v0.2.7/http/file_server.ts

The URL quickly disappears as its redirected to the source. This is confusing and makes discovering new URLs difficult.

It would also be good to have a simple directory listing when visiting https://deno.land/x/std@v0.2.7/http/

Must properly handle etag cache header.

**Comment by j-f1** [comment]
> It would also be good to have a simple directory listing when visiting https://deno.land/x/std@v0.2.7/http/

That could also redirect to the repo on GitHub.

**Comment by mtharrison** [comment]
Does this look ok for the pretty browser preview? If so I can make a PR.

<img width="1183" alt="Screenshot 2019-06-12 at 23 24 58" src="https://user-images.githubusercontent.com/916064/59390607-b3d9f900-8d69-11e9-8d62-0a02cde83ada.png">

**Comment by kt3k** [comment]
Seems resolved in #112
