### ISSUE TITLE
discussion: deprecate std modules in registry

### ISSUE THREAD

**Issue by hayd** [denoland/registry#70]
One of the recent issues was a directory that didn't exist in std (to ../utils.ts), this not have been a concern if using the `deno.land/std/` links everywhere rather than `deno.land/x/http` etc.

This would also adds weight to "this is a std lib module" as you can see it from the domain prefix.

This would be a breaking change...

**Comment by ry** [comment]
Yeah I’m in agreement.

**Comment by bartlomieju** [comment]
I'm all in for `deno.land/std/` :+1:

**Comment by hayd** [comment]
@ry Should we just rip the band-aid here?

**Comment by j-f1** [comment]
If you don’t want an immediate breaking change, you could put in a temporary file that re-exports from the new URL and logs a warning.

**Comment by ry** [comment]
I think we can just do a breaking change. But it would be good to add something to the tests that prevent people from registering the ones we have removed like "http", "net", etc
