### ISSUE TITLE
Fen can't be reach through https://deno.land/x/fen

### ISSUE THREAD

**Issue by mxz96102** [denoland/registry#75]
it seems something wrong with [https://deno.land/x/fen/server.ts](https://deno.land/x/fen/server.ts), 
I got a 503 error, is there something wrong with my pr or something with the server?

**Comment by hayd** [comment]
It looks like you missed a trailing slash:
```diff
-     "url": "https://raw.githubusercontent.com/fen-land/deno-fen/${b}", 
+     "url": "https://raw.githubusercontent.com/fen-land/deno-fen/${b}/", 
```

**Comment by mxz96102** [comment]
> It looks like you missed a trailing slash:
> 
> ```diff
> -     "url": "https://raw.githubusercontent.com/fen-land/deno-fen/${b}", 
> +     "url": "https://raw.githubusercontent.com/fen-land/deno-fen/${b}/", 
> ```

Oh, thanks, I will fix this right now
