### ISSUE TITLE
Add normalize-diacritics

### ISSUE THREAD

**Issue by motss** [denoland/registry#79]
I'd like to add my little module [normalize-diacritics][] to the registry but not sure if something like this is in the std. Is it going to cause any conflict?

[normalize-diacritics]: https://github.com/motss/normalize-diacritics/tree/deno

**Comment by ry** [comment]
Please do add it. (Use an underscore instead of dash tho for the module name)

**Comment by motss** [comment]
I've moved all my `deno` modules to a new repo to better align with the style guide of `deno`.

**Comment by zekth** [comment]
Looks like a polyfill of https://github.com/denoland/deno/issues/1952
