### ISSUE TITLE
HTML source code shouldn't have blue background

### ISSUE THREAD

**Issue by ry** [denoland/registry#97]
Ideally it would look like this

<img width="1151" alt="Screen Shot 2019-06-18 at 12 29 38 PM" src="https://user-images.githubusercontent.com/80/59702001-c5d1f680-91c4-11e9-91e8-4768387a6850.png">

cc  @mtharrison

**Comment by mtharrison** [comment]
@ry is this just for `registry` or should it be a general update to style.css?

**Comment by ry** [comment]
@mtharrison Probably a general update to style.css would be ideal

**Comment by bartlomieju** [comment]
What about all those people (including me) who prefer dark mode? Ideally we should aspire to have a toggle that switches color scheme 😉

**Comment by ry** [comment]
We can consider themes in 2020... at the moment there's functionality missing and that should be done first.
