### ISSUE TITLE
HTML source code should be able to select lines based on anchor tags 

### ISSUE THREAD

**Issue by ry** [denoland/registry#98]
I can select a single line of source code on github using the anchor tag: https://github.com/denoland/deno_std/blob/master/http/server.ts#L7

It would be nice to be able to do this on deno.land too: https://deno.land/std/http/server.ts#L7

**Comment by j-f1** [comment]
Should ranges also be supported? https://github.com/denoland/deno_std/blob/master/http/server.ts#L18-L24

**Comment by ry** [comment]
Yes, that also!

**Comment by j-f1** [comment]
Working on this.
